package presentation;

import DAOs.AppointmentManager;
import DAOs.PatientDAO;
import IDAOs.IAppointmentManager;
import DTOs.NewAppointmentDTO;
import DTOs.ExistentDoctorDTO;
import java.util.Calendar;
import DTOs.ExistentPatientDTO;
import IDAOs.IPatientDAO;
import POJOs.AppointmentPOJO;
import POJOs.PatientPOJO;
import Tools.Pintar;

public class JFrameConfirmAppointment extends javax.swing.JFrame {

    private NewAppointmentDTO newAppointmentDTO;
    private ExistentPatientDTO patientDTO;
    private ExistentDoctorDTO doctorDTO;

    /**
     * Creates new form AgendarCita
     */
    public JFrameConfirmAppointment(NewAppointmentDTO newAppointmentDTO, ExistentPatientDTO patientDTO) {
        this.patientDTO = patientDTO;
        this.newAppointmentDTO = newAppointmentDTO;
        initComponents();
        this.lblName.setText(newAppointmentDTO.getPatient().getName());
        this.lblDoctor.setText(newAppointmentDTO.getDoctor().getName());
        String dateString = "" + newAppointmentDTO.getAppointmentDate().get(Calendar.DATE) + "/" + (newAppointmentDTO.getAppointmentDate().get(Calendar.MONTH)+1) + "/" + newAppointmentDTO.getAppointmentDate().get(Calendar.YEAR) + "  " + newAppointmentDTO.getAppointmentDate().get(Calendar.HOUR_OF_DAY) + ":00";
        this.lblDate.setText(dateString);
        this.lblSpecialitazion.setText(newAppointmentDTO.getDoctor().getSpecialization().toString());
        this.lblNote.setText(newAppointmentDTO.getNote());
        Pintar imagen = new Pintar();
        imagen.PintarImagen(lblLogo, "src/main/java/Fotos/FondoLogin.jpg");
        imagen.PintarImagen(lblFondo, "src/main/java/Fotos/pngtree-image-of-futuristic-medical-hospital-room-picture-image_2736851.jpg");
        imagen.PintarImagen(lblBlue, "src/main/java/Fotos/abstract-template-blue-background-white-squares-free-vector.jpg");
        imagen.PintarImagen(lblBackLogin, "src/main/java/Fotos/abstract-blue-gradient-curved-shapes-on-white-background-free-vector.jpg");

        
    }

    public JFrameConfirmAppointment(NewAppointmentDTO newAppointmentDTO, ExistentDoctorDTO doctorDTO) {

        this.doctorDTO = doctorDTO;
        this.newAppointmentDTO = newAppointmentDTO;

        initComponents();
        this.lblName.setText(newAppointmentDTO.getPatient().getName());
        this.lblDoctor.setText(newAppointmentDTO.getDoctor().getName());
        String dateString = "" + newAppointmentDTO.getAppointmentDate().get(Calendar.DATE) + "/" + (newAppointmentDTO.getAppointmentDate().get(Calendar.MONTH)+1) + "/" + newAppointmentDTO.getAppointmentDate().get(Calendar.YEAR)  + "  " + newAppointmentDTO.getAppointmentDate().get(Calendar.HOUR_OF_DAY) + ":00";
        this.lblDate.setText(dateString);
        this.lblSpecialitazion.setText(newAppointmentDTO.getDoctor().getSpecialization().toString());
        this.lblNote.setText(newAppointmentDTO.getNote());
        Pintar imagen = new Pintar();
        imagen.PintarImagen(lblLogo, "src/main/java/Fotos/FondoLogin.jpg");
        imagen.PintarImagen(lblFondo, "src/main/java/Fotos/pngtree-image-of-futuristic-medical-hospital-room-picture-image_2736851.jpg");
        imagen.PintarImagen(lblBlue, "src/main/java/Fotos/abstract-template-blue-background-white-squares-free-vector.jpg");
        imagen.PintarImagen(lblBackLogin, "src/main/java/Fotos/abstract-blue-gradient-curved-shapes-on-white-background-free-vector.jpg");

        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        FondoPanel5 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        btnEdit = new javax.swing.JButton();
        btnConfirm = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        lblDate = new javax.swing.JLabel();
        lblDoctor = new javax.swing.JLabel();
        lblSpecialitazion = new javax.swing.JLabel();
        lblNote = new javax.swing.JLabel();
        lblBackLogin = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblLogo = new javax.swing.JLabel();
        lblBlue = new javax.swing.JLabel();
        lblFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        FondoPanel5.setBackground(new java.awt.Color(255, 255, 255));
        FondoPanel5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        FondoPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(51, 102, 255));
        jLabel10.setText("Doctotor");
        FondoPanel5.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 260, -1, -1));

        jLabel2.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 102, 255));
        jLabel2.setText("Name");
        FondoPanel5.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 220, -1, -1));

        jLabel11.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(51, 102, 255));
        jLabel11.setText("Note");
        FondoPanel5.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 390, -1, -1));

        btnEdit.setBackground(new java.awt.Color(255, 255, 255));
        btnEdit.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        btnEdit.setForeground(new java.awt.Color(51, 102, 255));
        btnEdit.setText("EDIT");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });
        FondoPanel5.add(btnEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 450, 120, 50));

        btnConfirm.setBackground(new java.awt.Color(255, 255, 255));
        btnConfirm.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        btnConfirm.setForeground(new java.awt.Color(51, 102, 255));
        btnConfirm.setText("CONFIRM");
        btnConfirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmActionPerformed(evt);
            }
        });
        FondoPanel5.add(btnConfirm, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 450, 120, 50));

        jLabel3.setFont(new java.awt.Font("Verdana", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 102, 255));
        jLabel3.setText("Confirm Appointment");
        FondoPanel5.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, -1, -1));

        jLabel8.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(51, 102, 255));
        jLabel8.setText("Specialization");
        FondoPanel5.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 350, -1, -1));

        jLabel9.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(51, 102, 255));
        jLabel9.setText("Date");
        FondoPanel5.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 300, -1, -1));

        lblName.setBackground(new java.awt.Color(153, 255, 255));
        lblName.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        lblName.setForeground(new java.awt.Color(51, 102, 255));
        FondoPanel5.add(lblName, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 210, 156, 26));

        lblDate.setBackground(new java.awt.Color(153, 255, 255));
        lblDate.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        lblDate.setForeground(new java.awt.Color(51, 102, 255));
        FondoPanel5.add(lblDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 290, 156, 26));

        lblDoctor.setBackground(new java.awt.Color(153, 255, 255));
        lblDoctor.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        lblDoctor.setForeground(new java.awt.Color(51, 102, 255));
        FondoPanel5.add(lblDoctor, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 250, 156, 26));

        lblSpecialitazion.setBackground(new java.awt.Color(153, 255, 255));
        lblSpecialitazion.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        lblSpecialitazion.setForeground(new java.awt.Color(51, 102, 255));
        FondoPanel5.add(lblSpecialitazion, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 340, 156, 26));

        lblNote.setBackground(new java.awt.Color(153, 255, 255));
        lblNote.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        lblNote.setForeground(new java.awt.Color(51, 102, 255));
        FondoPanel5.add(lblNote, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 380, 156, 26));
        FondoPanel5.add(lblBackLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 180, 350, 250));

        jLabel4.setFont(new java.awt.Font("Stencil", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 51, 255));
        jLabel4.setText("General Hospital");
        FondoPanel5.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, 249, 36));

        lblLogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        FondoPanel5.add(lblLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 40, 40));

        lblBlue.setBackground(new java.awt.Color(51, 102, 255));
        lblBlue.setForeground(new java.awt.Color(51, 102, 255));
        FondoPanel5.add(lblBlue, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 910, 60));
        FondoPanel5.add(lblFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 860, 530));

        getContentPane().add(FondoPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 600));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        // TODO add your handling code here:
        if (doctorDTO == null) {

            JFrameRegisterAppointment register = new JFrameRegisterAppointment(newAppointmentDTO, patientDTO);
            register.setVisible(true);
            this.dispose();
        } else {
            JFrameRegisterAppointment register = new JFrameRegisterAppointment(newAppointmentDTO, doctorDTO);
            register.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_btnEditActionPerformed

    private void btnConfirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmActionPerformed
        // TODO add your handling code here:
        IAppointmentManager appointmentManager = new AppointmentManager();
        AppointmentPOJO appointmentPOJO = appointmentManager.DtoToEntity(newAppointmentDTO);
        appointmentManager.createAppointment(appointmentPOJO);

        if (doctorDTO == null) {
            JFrameInitialPatient frameInitialPatient = new JFrameInitialPatient(patientDTO.getId());
            frameInitialPatient.setVisible(true);
            this.dispose();

        } else {
            JFrameInitialMedicos medic = new JFrameInitialMedicos(doctorDTO.getId());
            medic.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_btnConfirmActionPerformed

//    /**
//     * @param args the command line arguments
//     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(JFrameRegisterAppointment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(JFrameRegisterAppointment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(JFrameRegisterAppointment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(JFrameRegisterAppointment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new JFrameRegisterAppointment().setVisible(true);
//            }
//        });
//    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel FondoPanel5;
    private javax.swing.JButton btnConfirm;
    private javax.swing.JButton btnEdit;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lblBackLogin;
    private javax.swing.JLabel lblBlue;
    private javax.swing.JLabel lblDate;
    private javax.swing.JLabel lblDoctor;
    private javax.swing.JLabel lblFondo;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblNote;
    private javax.swing.JLabel lblSpecialitazion;
    // End of variables declaration//GEN-END:variables
}
