package presentation;

import DAOs.PatientDAO;
import DAOs.UserDAO;
import com.toedter.calendar.JDateChooser;
import java.util.Calendar;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import IDAOs.IPatientDAO;
import DTOs.NewPatientDTO;
import IDAOs.IUserDAO;
import DTOs.NewUserDTO;
import POJOs.PatientPOJO;
import Tools.Pintar;

public class JFrameRegisterPatient extends javax.swing.JFrame {

    private NewUserDTO userDTO;
    private NewUserDTO userDTOAdmin;
    private JDateChooser dateChooser;

    /**
     * Creates new form RegistroPaciente
     */
    public JFrameRegisterPatient(NewUserDTO userDTO) {
        initComponents();
        txtOther.setEditable(false);
        this.userDTO = userDTO;
        dateChooser();
        this.setTitle("Registro Paciente");
        Pintar imagen = new Pintar();
        imagen.PintarImagen(lblLogo, "src/main/java/Fotos/FondoLogin.jpg");
        imagen.PintarImagen(lblFondo, "src/main/java/Fotos/pngtree-image-of-futuristic-medical-hospital-room-picture-image_2736851.jpg");

        imagen.PintarImagen(lblBlue, "src/main/java/Fotos/abstract-template-blue-background-white-squares-free-vector.jpg");
        imagen.PintarImagen(lblFondoRegister, "src/main/java/Fotos/abstract-blue-gradient-curved-shapes-on-white-background-free-vector.jpg");
    }

    public JFrameRegisterPatient(NewUserDTO userDTO, NewUserDTO userDTOAdmin) {

        initComponents();
        txtOther.setEditable(false);
        this.userDTO = userDTO;
        dateChooser();
        this.setTitle("Registro Paciente");
        this.userDTOAdmin = userDTOAdmin;

    }

    public void dateChooser() {

        this.dateChooser = new JDateChooser();
        this.dateChooser.setBounds(lblDate.getBounds());
        this.jPanel1.add(dateChooser);

    }

    public void limitarFecha() {
        Calendar fechaMinima = Calendar.getInstance();
        fechaMinima.set(Calendar.YEAR, -18);
        Date minimo = fechaMinima.getTime();
        Calendar fechaMaxima = Calendar.getInstance();
        fechaMaxima.add(Calendar.DATE, -1);
        Date maximo = fechaMaxima.getTime();
        dateChooser.setSelectableDateRange(minimo, maximo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        FondoPanel = new javax.swing.JPanel();
        Iniciar_Sesion = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        Usuario = new javax.swing.JLabel();
        txtFirstName = new javax.swing.JTextField();
        txtCurp = new javax.swing.JTextField();
        Usuario3 = new javax.swing.JLabel();
        Usuario4 = new javax.swing.JLabel();
        txtColony = new javax.swing.JTextField();
        Usuario5 = new javax.swing.JLabel();
        txtStreet = new javax.swing.JTextField();
        Usuario7 = new javax.swing.JLabel();
        txtPhone = new javax.swing.JTextField();
        Usuario6 = new javax.swing.JLabel();
        txtSecurityNumber = new javax.swing.JTextField();
        Usuario8 = new javax.swing.JLabel();
        btnAceptar = new javax.swing.JButton();
        FondoGenero = new javax.swing.JPanel();
        Usuario1 = new javax.swing.JLabel();
        cbxMale = new javax.swing.JCheckBox();
        cbxFamele = new javax.swing.JCheckBox();
        Usuario11 = new javax.swing.JLabel();
        txtOther = new javax.swing.JTextField();
        cbxOther = new javax.swing.JCheckBox();
        txtZipCode = new javax.swing.JTextField();
        Usuario9 = new javax.swing.JLabel();
        txtSecondName = new javax.swing.JTextField();
        Usuario13 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lblLogo = new javax.swing.JLabel();
        lblBlue = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        lblDate = new javax.swing.JLabel();
        Usuario12 = new javax.swing.JLabel();
        lblFondoRegister = new javax.swing.JLabel();
        lblFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(900, 600));

        FondoPanel.setBackground(new java.awt.Color(255, 255, 255));
        FondoPanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        FondoPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Iniciar_Sesion.setFont(new java.awt.Font("Stencil", 1, 36)); // NOI18N
        Iniciar_Sesion.setForeground(new java.awt.Color(51, 153, 255));
        Iniciar_Sesion.setText("Register Patient");
        FondoPanel.add(Iniciar_Sesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, 360, -1));

        txtName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameActionPerformed(evt);
            }
        });
        txtName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNameKeyReleased(evt);
            }
        });
        FondoPanel.add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 190, 220, -1));

        Usuario.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        Usuario.setForeground(new java.awt.Color(51, 102, 255));
        Usuario.setText("Names");
        FondoPanel.add(Usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 170, -1, -1));

        txtFirstName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtFirstNameKeyReleased(evt);
            }
        });
        FondoPanel.add(txtFirstName, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 190, 159, -1));
        FondoPanel.add(txtCurp, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 390, 180, -1));

        Usuario3.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        Usuario3.setForeground(new java.awt.Color(51, 102, 255));
        Usuario3.setText("CURP");
        FondoPanel.add(Usuario3, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 370, -1, -1));

        Usuario4.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        Usuario4.setForeground(new java.awt.Color(51, 102, 255));
        Usuario4.setText("First Last Name");
        FondoPanel.add(Usuario4, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 170, -1, -1));
        FondoPanel.add(txtColony, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 330, 180, -1));

        Usuario5.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        Usuario5.setForeground(new java.awt.Color(51, 102, 255));
        Usuario5.setText("Colony");
        FondoPanel.add(Usuario5, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 310, -1, -1));

        txtStreet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtStreetActionPerformed(evt);
            }
        });
        FondoPanel.add(txtStreet, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 390, 130, -1));

        Usuario7.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        Usuario7.setForeground(new java.awt.Color(255, 255, 255));
        Usuario7.setText("Street");
        FondoPanel.add(Usuario7, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 370, -1, -1));
        FondoPanel.add(txtPhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 390, 230, -1));

        Usuario6.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        Usuario6.setForeground(new java.awt.Color(51, 102, 255));
        Usuario6.setText("Phone Number");
        FondoPanel.add(Usuario6, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 370, -1, -1));
        FondoPanel.add(txtSecurityNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 330, 130, -1));

        Usuario8.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        Usuario8.setForeground(new java.awt.Color(255, 255, 255));
        Usuario8.setText("Insurance Number");
        FondoPanel.add(Usuario8, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 310, -1, -1));

        btnAceptar.setBackground(new java.awt.Color(255, 255, 255));
        btnAceptar.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        btnAceptar.setForeground(new java.awt.Color(51, 102, 255));
        btnAceptar.setText("ACCEPT");
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });
        FondoPanel.add(btnAceptar, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 500, 200, 50));

        FondoGenero.setBackground(new java.awt.Color(255, 255, 255));
        FondoGenero.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        Usuario1.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        Usuario1.setForeground(new java.awt.Color(51, 102, 255));
        Usuario1.setText("Sex");

        cbxMale.setFont(new java.awt.Font("Roboto", 2, 12)); // NOI18N
        cbxMale.setText("Male");
        cbxMale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxMaleActionPerformed(evt);
            }
        });

        cbxFamele.setFont(new java.awt.Font("Roboto", 2, 12)); // NOI18N
        cbxFamele.setText("Female");
        cbxFamele.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxFameleActionPerformed(evt);
            }
        });

        Usuario11.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        Usuario11.setForeground(new java.awt.Color(51, 102, 255));
        Usuario11.setText("Other");

        txtOther.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtOtherKeyReleased(evt);
            }
        });

        cbxOther.setFont(new java.awt.Font("Roboto", 2, 12)); // NOI18N
        cbxOther.setText("Other");
        cbxOther.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxOtherActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout FondoGeneroLayout = new javax.swing.GroupLayout(FondoGenero);
        FondoGenero.setLayout(FondoGeneroLayout);
        FondoGeneroLayout.setHorizontalGroup(
            FondoGeneroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FondoGeneroLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(FondoGeneroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Usuario1)
                    .addGroup(FondoGeneroLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(cbxMale)
                        .addGap(34, 34, 34)
                        .addComponent(cbxFamele)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addComponent(cbxOther)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(FondoGeneroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Usuario11)
                    .addComponent(txtOther, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32))
        );
        FondoGeneroLayout.setVerticalGroup(
            FondoGeneroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FondoGeneroLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(FondoGeneroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Usuario11)
                    .addComponent(Usuario1))
                .addGap(1, 1, 1)
                .addGroup(FondoGeneroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(FondoGeneroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cbxMale)
                        .addComponent(cbxFamele))
                    .addGroup(FondoGeneroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtOther, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cbxOther)))
                .addContainerGap(10, Short.MAX_VALUE))
        );

        FondoPanel.add(FondoGenero, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 230, -1, -1));
        FondoPanel.add(txtZipCode, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 330, 180, -1));

        Usuario9.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        Usuario9.setForeground(new java.awt.Color(51, 102, 255));
        Usuario9.setText("Zipcode");
        FondoPanel.add(Usuario9, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 310, -1, -1));

        txtSecondName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSecondNameKeyReleased(evt);
            }
        });
        FondoPanel.add(txtSecondName, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 190, 159, -1));

        Usuario13.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        Usuario13.setForeground(new java.awt.Color(255, 255, 255));
        Usuario13.setText("Second Last Name");
        FondoPanel.add(Usuario13, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 160, -1, -1));

        jLabel1.setFont(new java.awt.Font("Stencil", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 51, 255));
        jLabel1.setText("General Hospital");
        FondoPanel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, 249, 36));

        lblLogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        FondoPanel.add(lblLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 40, 40));

        lblBlue.setBackground(new java.awt.Color(51, 102, 255));
        lblBlue.setForeground(new java.awt.Color(51, 102, 255));
        FondoPanel.add(lblBlue, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 910, 60));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        Usuario12.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        Usuario12.setForeground(new java.awt.Color(51, 102, 255));
        Usuario12.setText("Birth Date");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblDate, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(Usuario12)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(Usuario12)
                .addGap(13, 13, 13)
                .addComponent(lblDate, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 14, Short.MAX_VALUE))
        );

        FondoPanel.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(623, 220, 180, 70));
        FondoPanel.add(lblFondoRegister, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 120, 720, 360));
        FondoPanel.add(lblFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 830, 500));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(FondoPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(FondoPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
        // TODO add your handling code here:

        String names = txtName.getText();
        String firstName = txtFirstName.getText();
        String secondName = txtSecondName.getText();
        String colony = txtColony.getText();
        String zipCodeS = txtZipCode.getText();
        String curp = txtCurp.getText();
        String phone = txtPhone.getText();
        String socialNumber = txtSecurityNumber.getText();
        String street = txtStreet.getText();
        Calendar birthDate = dateChooser.getCalendar();
        String sex = "";
        
        if (cbxMale.isSelected()) {
            sex = "M";
        } else if (cbxFamele.isSelected()) {
            sex = "F";
        } else if (cbxOther.isSelected()) {
            sex = txtOther.getText();
        } else {
            sex = "";
        }

        if (names.isEmpty() || firstName.isEmpty() || secondName.isEmpty() || colony.isEmpty()
                || zipCodeS.isEmpty() || curp.isEmpty() || phone.isEmpty() || socialNumber.isEmpty()
                || street.isEmpty() || sex.isEmpty() || birthDate == null) {
            JOptionPane.showMessageDialog(null, "Favor de llenar todos los campos", "Error", JOptionPane.ERROR_MESSAGE);
        }
        if (!names.matches("[a-zA-ZñÑáéíóúÁÉÍÓÚ\\s]+") || !firstName.matches("[a-zA-ZñÑáéíóúÁÉÍÓÚ]+") || !secondName.matches("[a-zA-ZñÑáéíóúÁÉÍÓÚ]+")) {
            JOptionPane.showMessageDialog(null, "Names can only contain leters", "Error", JOptionPane.INFORMATION_MESSAGE);
        } else {

            int zipCode = Integer.parseInt(zipCodeS);
            NewPatientDTO newPatientDTO = new NewPatientDTO(
                    names, firstName, secondName, birthDate, sex, curp, socialNumber, phone, street, colony, zipCode
            );

            try {
                //Creamos paciente nuevo
                IPatientDAO patientSystem = new PatientDAO();
                PatientPOJO patientPOJO = patientSystem.DtoToEntity(newPatientDTO);
                patientSystem.registerPatient(patientPOJO);
                
                IUserDAO userSystem = new UserDAO();
                PatientPOJO patientPOJO1 = patientSystem.searchPatientByCurp(patientPOJO.getCurp());
                userDTO.setType("PATIENT");
                userDTO.setIdOwner(patientPOJO1.getId());
                userSystem.registerUser(userSystem.DtoToEntity(userDTO));

            } catch (Exception ex) {
                Logger.getLogger(JFrameRegisterPatient.class.getName()).log(Level.SEVERE, "Error al persistir", ex);
            }

            if (userDTOAdmin == null) {
                JFrameLogin frameLogin = new JFrameLogin();
                frameLogin.setVisible(true);
                this.dispose();
            } else {
                JFrameAdministrator admin = new JFrameAdministrator(userDTOAdmin.getCurp(), userDTOAdmin.getPassword());
                admin.setVisible(true);
                this.dispose();
            }
        }
    }//GEN-LAST:event_btnAceptarActionPerformed

    private void txtNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNameActionPerformed

    private void cbxMaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxMaleActionPerformed
        // TODO add your handling code here:
        cbxFamele.setSelected(false);
        cbxOther.setSelected(false);
        txtOther.setEditable(false);
    }//GEN-LAST:event_cbxMaleActionPerformed

    private void cbxFameleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxFameleActionPerformed
        // TODO add your handling code here:

        cbxMale.setSelected(false);
        txtOther.setEditable(false);
        cbxOther.setSelected(false);

    }//GEN-LAST:event_cbxFameleActionPerformed

    private void cbxOtherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxOtherActionPerformed
        // TODO add your handling code here:
        cbxMale.setSelected(false);
        cbxFamele.setSelected(false);
        txtOther.setEditable(true);
    }//GEN-LAST:event_cbxOtherActionPerformed

    private void txtStreetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtStreetActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtStreetActionPerformed

    private void txtNameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNameKeyReleased
        // TODO add your handling code here:
        if(!txtName.getText().matches("[a-zA-ZñÑáéíóúÁÉÍÓÚ\\s]+")){
            JOptionPane.showMessageDialog(null, "Name can only contain leters", "Error", JOptionPane.INFORMATION_MESSAGE);
            txtName.setText("");
        }
    }//GEN-LAST:event_txtNameKeyReleased

    private void txtFirstNameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFirstNameKeyReleased
        // TODO add your handling code here:
        if(!txtFirstName.getText().matches("[a-zA-ZñÑáéíóúÁÉÍÓÚ\\s]+")){
            JOptionPane.showMessageDialog(null, "First name can only contain leters", "Error", JOptionPane.INFORMATION_MESSAGE);
            txtFirstName.setText("");
        }
    }//GEN-LAST:event_txtFirstNameKeyReleased

    private void txtSecondNameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSecondNameKeyReleased
        // TODO add your handling code here:
        if(!txtSecondName.getText().matches("[a-zA-ZñÑáéíóúÁÉÍÓÚ\\s]+")){
            JOptionPane.showMessageDialog(null, "Second name can only contain leters", "Error", JOptionPane.INFORMATION_MESSAGE);
            txtSecondName.setText("");
        }
        
    }//GEN-LAST:event_txtSecondNameKeyReleased

    private void txtOtherKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtOtherKeyReleased
        // TODO add your handling code here:
        if(!txtOther.getText().matches("[a-zA-ZñÑáéíóúÁÉÍÓÚ\\s]+")){
            JOptionPane.showMessageDialog(null, "Other can only contain leters", "Error", JOptionPane.INFORMATION_MESSAGE);
            txtOther.setText("");
        }
    }//GEN-LAST:event_txtOtherKeyReleased

//    /**
//     * @param args the command line arguments
//     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//     txtFirstNamer-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(JFRegisterPatient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(JFRegisterPatient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(JFRegisterPatient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(JFRegisterPatient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new JFRegisterPatient().setVisible(true);
//            }
//        });
//    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel FondoGenero;
    private javax.swing.JPanel FondoPanel;
    private javax.swing.JLabel Iniciar_Sesion;
    private javax.swing.JLabel Usuario;
    private javax.swing.JLabel Usuario1;
    private javax.swing.JLabel Usuario11;
    private javax.swing.JLabel Usuario12;
    private javax.swing.JLabel Usuario13;
    private javax.swing.JLabel Usuario3;
    private javax.swing.JLabel Usuario4;
    private javax.swing.JLabel Usuario5;
    private javax.swing.JLabel Usuario6;
    private javax.swing.JLabel Usuario7;
    private javax.swing.JLabel Usuario8;
    private javax.swing.JLabel Usuario9;
    private javax.swing.JButton btnAceptar;
    private javax.swing.JCheckBox cbxFamele;
    private javax.swing.JCheckBox cbxMale;
    private javax.swing.JCheckBox cbxOther;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblBlue;
    private javax.swing.JLabel lblDate;
    private javax.swing.JLabel lblFondo;
    private javax.swing.JLabel lblFondoRegister;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JTextField txtColony;
    private javax.swing.JTextField txtCurp;
    private javax.swing.JTextField txtFirstName;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtOther;
    private javax.swing.JTextField txtPhone;
    private javax.swing.JTextField txtSecondName;
    private javax.swing.JTextField txtSecurityNumber;
    private javax.swing.JTextField txtStreet;
    private javax.swing.JTextField txtZipCode;
    // End of variables declaration//GEN-END:variables
}
